### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ovanderzee** [dhurlburtusa/js-bag#1]
Hi, I came across your work on npmjs.com and I wanted to contact you. About __my-lib__, among others, you state "Dead package. Let me know if you would like me to transfer ownership." But you seem to very withholding with your contactinfo.

I am interested in developing my-lib. Since I let the same functions recurring again and again, it's time for a library. The functions are not very connected, so 'my-lib' would be a good name.
In case you need the greeting function, I would be happy to include it.

Would you pass the ownership to me? 
See https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

Many thanks,
https://www.npmjs.com/~ovanderzee

**Comment by dhurlburtusa** [comment]
Hello Onno,

I saw the email from Eva from NPM. I replied back authorizing the transfer. So, hopefully you'll be the owner of `my-lib` later today or tomorrow.

Please let me know if you need anything else from me for the transfer.

BTW, another option is to use scopes. Your NPM scope is `ovanderzee`. So, if you want, you can publish the `@ovanderzee/my-lib` package.

Either way, thanks for reaching out and best of luck.

**Comment by ovanderzee** [comment]
Great, thank you!

**Comment by dhurlburtusa** [comment]
Looks like the transfer was successful. Closing.
